services:
    btn_user.btn_user_provider:
        class: Btn\UserBundle\Security\BtnUserProvider
        public: false
        arguments: ["@fos_user.user_manager"]

    btn_user.registration.form.type:
        class: Btn\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btn_user_registration }